import erroraffirmations

raise Exception('Something went wrong')